export const shopMahsulotlar = [
    {
      id: 101,
      nom: "Macbook Air 2023 8GB RAM - 256GB SSD",
      narx: 825,
      eski: 965,
      reyting: 4.7,
      sharh: 12,
      belgi: "New",
      chegirma: "10%",
      kategoriya: "Smartphone",
      sub: "iPhone",
      brand: "Apple",
      rang: "black",
      xotira: "256GB",
      rasm: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: 102,
      nom: "Apple iPhone 14 - 128GB Midnight",
      narx: 125,
      eski: 145,
      reyting: 4.6,
      sharh: 12,
      belgi: "New",
      chegirma: "10%",
      kategoriya: "Smartphone",
      sub: "iPhone",
      brand: "Apple",
      rang: "gray",
      xotira: "128GB",
      rasm: "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: 103,
      nom: "Apple Watch Series 8 GPS - Aluminum Case",
      narx: 425,
      eski: 485,
      reyting: 4.5,
      sharh: 12,
      belgi: "New",
      chegirma: "10%",
      kategoriya: "Watches",
      sub: "Apple Watch",
      brand: "Apple",
      rang: "white",
      xotira: "64GB",
      rasm: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: 104,
      nom: "AirPods (3rd generation) - Lightning Charging Case",
      narx: 65,
      eski: 85,
      reyting: 4.6,
      sharh: 12,
      belgi: "New",
      chegirma: "10%",
      kategoriya: "Audio",
      sub: "Headphones",
      brand: "Apple",
      rang: "white",
      xotira: "64GB",
      rasm: "https://images.unsplash.com/photo-1585386959984-a41552231693?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: 105,
      nom: "Apple iPad Pro 11 M1 2021 WiFi 128GB",
      narx: 825,
      eski: 935,
      reyting: 4.7,
      sharh: 12,
      belgi: "New",
      chegirma: "10%",
      kategoriya: "Tablet",
      sub: "iPad",
      brand: "Apple",
      rang: "gray",
      xotira: "128GB",
      rasm: "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: 106,
      nom: "Smart TV Samsung 4K 75 inch UHD",
      narx: 425,
      eski: 485,
      reyting: 4.4,
      sharh: 12,
      belgi: "New",
      chegirma: "10%",
      kategoriya: "TV",
      sub: "TV",
      brand: "Samsung",
      rang: "black",
      xotira: "512GB",
      rasm: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: 107,
      nom: "MX MASTER 3S Performance Wireless Mouse",
      narx: 125,
      eski: 145,
      reyting: 4.6,
      sharh: 12,
      belgi: "New",
      chegirma: "10%",
      kategoriya: "Accessory",
      sub: "Accessory",
      brand: "Dell",
      rang: "black",
      xotira: "64GB",
      rasm: "https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: 108,
      nom: "Logitech K650 Wireless Solar Keyboard",
      narx: 105,
      eski: 150,
      reyting: 4.5,
      sharh: 12,
      belgi: "New",
      chegirma: "10%",
      kategoriya: "Laptop",
      sub: "Laptop",
      brand: "Lenovo",
      rang: "gray",
      xotira: "1TB",
      rasm: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: 109,
      nom: "JBL WH-CH520 Wireless Bluetooth Headphones",
      narx: 225,
      eski: 265,
      reyting: 4.6,
      sharh: 12,
      belgi: "New",
      chegirma: "10%",
      kategoriya: "Audio",
      sub: "Headphones",
      brand: "Nokia",
      rang: "blue",
      xotira: "128GB",
      rasm: "https://images.unsplash.com/photo-1518441902117-f0a3d3b6c3d7?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: 110,
      nom: "Canon EOS 450D Lens Kit 18-55mm",
      narx: 105,
      eski: 150,
      reyting: 4.4,
      sharh: 12,
      belgi: "New",
      chegirma: "10%",
      kategoriya: "Cameras",
      sub: "Cameras",
      brand: "Dell",
      rang: "black",
      xotira: "256GB",
      rasm: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=900&q=80",
    },
  ];
  
  export const shopRanglar = [
    { id: "white", nom: "White" },
    { id: "gray", nom: "Gray" },
    { id: "black", nom: "Black" },
    { id: "blue", nom: "Blue" },
    { id: "green", nom: "Green" },
    { id: "orange", nom: "Orange" },
  ];
  
  export const shopXotira = ["64GB", "128GB", "256GB", "512GB", "1TB"];
  
  export const shopBrandlar = ["Apple", "Samsung", "Dell", "Nokia", "Lenovo"];
  
  export const shopKategoriya = [
    {
      nom: "Smartphone",
      sub: ["iPhone", "Samsung", "Nokia", "Oppo"],
    },
    { nom: "Laptop", sub: ["Laptop"] },
    { nom: "TV", sub: ["TV"] },
    { nom: "Audio", sub: ["Headphones"] },
    { nom: "Tablet", sub: ["iPad"] },
    { nom: "Accessory", sub: ["Accessory"] },
  ];
  
  export const shopTopRated = [
    { id: 1, narx: 55, nom: "JBL bluetooth", reyting: 4.7, sharh: 12 },
    { id: 2, narx: 895, nom: "Mac mini M2 512GB", reyting: 4.8, sharh: 12 },
    { id: 3, narx: 85, nom: "iPhone 14 Pro Max", reyting: 4.6, sharh: 12 },
  ];
  